language: go
go:
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - go get golang.org/x/lint/golint
script:
  - make
env:
  global:
    secure: ZFiOagCQr3cmYjJ+Rh64MpfJZHfiJvHVCCjbMbXC96khTPHlXe2dKbVRcRh26377E7j59nCQFnWq5t1USHIy+iPKpK41TQi32b9TOeMlCdN5PW6GqH/p+jOEiEJvvpwjYPXCsO8ZzYO3WCrxK7zcNMCj/6pkVTo/7SdbhyS29wRoncX91SxgusZ9N4msp0wWOMOAILxvai5Y6qDXMIpMUoeaIGqYAj7dIHFIgO2Eh8GynqnVFs6haEiTTbuqIcJN4YthLaAnUFg7UsGHpVYpYra0cfWarvi/EQYJppxys2FITJNxmrEjj8kCsDvFiB1tPaBu+YxeDB2L40VeuObQl6QiLYq7lxgIRbkDYGei0UCv/Jd01C+cXLPsXh/pJAia9PbC8K/9WZ216UVPHlil8kIDH7LUei7JLonKU0s0YUdksUSRw8/4nGkUUn9ha2tVQeFjg54g0V/TyYUJTyjGPMPOIUkt2BUdbqiENe9xOGEqL3Z0mzOj4FOqfMaNznFbaLsp22+5UKuW32Et27LgZvPFBzG5H/lqoG6js+VhN18WcDl3bDE2PQ5LsF+yykX1XI8puLVsw4UZ+psgm1Qr6Ib5puXiLC+Vpm0rPMfytxHbO+72q4oywTq9qiVcoZMnQPiYVCymXnFzBvOCKWBWc3wZ/CyKcolGad/O0Ys35qs=
